import Header from '@/components/Header/Header';
import './globals.css'
import { Poppins } from 'next/font/google'
import Footer from '@/components/Footer/Footer';

const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  style: ['italic', 'normal'],
  variable: '--font-poppins'
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body 
        className="font-poppins"
      >
        <Header />
        <main className="bg-primary-gradient min-h-screen">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
